language: node_js
node_js: stable

branches:
  only:
  - hexo-source

cache:
  directories:
  - node_modules

before_install:
  - export TZ='Asia/Shanghai'
  - npm install -g hexo-cli

install:
  - sudo apt-get update
  - sudo apt-get install -y graphicsmagick
  - npm update -g npm
  - npm install

script:
  - hexo clean
  - hexo douban
  - hexo g

after_success:
  - git config --global user.name "dldylan"
  - git config --global user.email "zjpjzdl@qq.com"
  - sed -i "s/GH_TOKEN/${GH_TOKEN}/g" ./_config.yml
  - sed -i "s/CODING_TOKEN/${CODING_TOKEN}/g" ./_config.yml
  - sed -i "s/BAIDU_TOKEN/${BAIDU_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy -m "Travis CI Build ${TRAVIS_BUILD_NUMBER}"

notifications:
email:
  recipients:
    - zjpjzdl@qq.com
  on_success: never # default: change
  on_failure: never # default: always