language: node_js
node_js: stable
branchs:
  only:
  - hexo-source
cache:
  directories:
  - node_modules
before_install:
  - npm install -g hexo-cli
install:
  - sudo apt-get update
  - sudo apt-get install -y graphicsmagick
  - npm update -g npm
  - npm install
script:
  - hexo clean
  - hexo g --debug
after_script:
  - git clone -b master https://github.com/dldylan/test.git .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config --global user.name "dldylan"
  - git config --global user.email "zjpjzdl@qq.com"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
env:
  global:
  - GH_REF: github.com/dldylan/test.git

  notifications:
  email:
    recipients:
      - zjpjzdl@qq.com
    on_success: never # default: change
    on_failure: never # default: always