backend:
  name: git-gateway
  repo: dldylan/blog
  branch: hexo-source # Branch to update (master by default)

media_folder: "/source/assets/" # Folder where user uploaded files should go
#public_folder: "/images/uploads"

publish_mode: editorial_workflow
site_url: https://blog.dongleizhang.com
display_url: https://blog.dongleizhang.com
show_preview_links: true
# slug:
#   encoding: "ascii" # default: unicode
#   clean_accents: true
#   sanitize_replacement: "_"  # default: "-"


collections: # A list of collections the CMS should be able to edit
  - name: "博客布置" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "博客布置" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/博客布置/" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "分类", name: "categories", widget: "list", allow_add: false, default: ["博客布置"]}
      - {label: "标签", name: "tags", widget: "list", allow_add: true, default: [""]}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "发布日期", name: "date", widget: "datetime", format: YYYY-MM-DD HH:mm:ss}
      - {label: "置顶", name: "top", widget: "boolean", default: false}
      - {label: "侧边目录", name: "toc", widget: "boolean", default: false}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}
  - name: "学术" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "学术" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/学术/" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "分类", name: "categories", widget: "list", allow_add: false, default: "学术"}
      - {label: "标签", name: "tags", widget: "list", allow_add: true, default: [""]}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "发布日期", name: "date", widget: "datetime", format: YYYY-MM-DD HH:mm:ss}
      - {label: "置顶", name: "top", widget: "boolean", default: false}
      - {label: "侧边目录", name: "toc", widget: "boolean", default: false}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}
  - name: "札记" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "札记" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/札记/" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "分类", name: "categories", widget: "list", allow_add: false, default: "札记"}
      - {label: "标签", name: "tags", widget: "list", allow_add: true, default: [""]}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "发布日期", name: "date", widget: "datetime", format: YYYY-MM-DD HH:mm:ss}
      - {label: "置顶", name: "top", widget: "boolean", default: false}
      - {label: "侧边目录", name: "toc", widget: "boolean", default: false}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}
  - name: "碎碎念" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "碎碎念" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/碎碎念/" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "分类", name: "categories", widget: "list", allow_add: false, default: "碎碎念"}
      - {label: "标签", name: "tags", widget: "list", allow_add: true, default: [""]}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "发布日期", name: "date", widget: "datetime", format: YYYY-MM-DD HH:mm:ss}
      - {label: "置顶", name: "top", widget: "boolean", default: false}
      - {label: "侧边目录", name: "toc", widget: "boolean", default: false}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}